### PR TITLE
[manager] Update database

### PR DESCRIPTION
**Pull request by anhdtn-1027**
[link redmine](https://edu-redmine.sun-asterisk.vn/issues/26761?issue_count=15&issue_position=1&next_issue_id=26616)

### CODE REVIEW

**Comment by anhdtn-1027** [comment]
image

**Comment by anhdtn-1027** [comment]
ready

**Comment by anhcnh-1028** [comment]
đã review

**Comment by manhbnt-0960** [comment]
commentd
link redmine đâu e

**Comment by manhbnt-0960** [comment]
commented

**Comment by anhdtn-1027** [comment]
em update link redmine ở đầu rồi ạ

**Comment by anhdtn-1027** [comment]
ready

**Pull request merged**
