### PR TITLE
[manager] Active inactive events

### PR DESCRIPTION
**Pull request by anhdtn-1027**
image

### CODE REVIEW

**Comment by anhdtn-1027** [comment]
link edu-redmine: 
https://edu-redmine.sun-asterisk.vn/issues/26512issue_count=19&issue_position=14&next_issue_id=26510&prev_issue_id=26514

**Comment by anhdtn-1027** [comment]
image
image

**Comment by anhdtn-1027** [comment]
ready

**Comment by manhbnt-0960** [comment]
commented

**Comment by manhbnt-0960** [comment]
merged

**Pull request merged**
